services:
  backend:
    build: ./clinica
    #ports:
    #  - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clinica
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: cachorro
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    #ports:
    #- "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cachorro
      POSTGRES_DB: clinica
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
      build: ./frontend
      ports:
        - "3000:80"
      environment:
        REACT_APP_API_URL: http://backend:8080
      depends_on:
        - backend
      networks:
        - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
