apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.name }}-credentials
type: Opaque
stringData:
  # As mesmas credenciais do seu docker-compose
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "cachorro"