apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
  selector:
    app: {{ .Values.frontend.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: IfNotPresent # Essencial para usar imagens locais
        ports:
        - containerPort: {{ .Values.frontend.port }}